config/routes.rb
ItemGuide::Application.routes.draw do
  get "item/index", :as =>:item_index

  get "equipment/index", :as => :home
  get "equipment/show/:name" => 'equipment#show' , :as => :show_equipment
  get "item/show/:name" => 'item#show', :as => :show_item

    root :to => 'equipment#index'

end

app/models/equipment.rb
class Equipment < ActiveRecord::Base

  def get_item #corresponding item record
    Item.find_by_name(name)
  end
      
  def basic_stats
      return {:type => item_type,
              :element => element,
              :register? => register,
              :buy => (buy==0)? "Not purchasable" : "#{buy} G",
              :sell => "#{sell} G"
              }
  end
  def spec_stats
    if weapon?
      return {:range => range,
              :height => height,
              :"weapon slot 1" => weapon1,
              :"weapon slot 2" => weapon2,
              :"weapon slot 3" => weapon3,
              :"weapon slot 4" => weapon4,
              }
    else
      return {:"absorbs element" => absorb,
              :autoskill => autoskill,
              :"autoskill slots" => autoskill_slot_count}
    end
  end
  
  def eqp_stats
    return collect_stats([:atk, :def, :hit, :avd, :mag])
  end
  
  def char_stats
    return collect_stats([:str, :vit, :agl, :int, :luk])
  end
  
  def misc_stats
    return collect_stats([:ap, :cost])
  end
  
  def collect_stats(stats)
    #Since cost at level 1 is not defined, put a temporary variable
    cost1 = "-"
    return Hash[stats.collect {|field| [field, (1..5).map {|n| eval("#{field}#{n}")}]}]
  end
  
  def invents_into
    get_item.invents
  end
  
  def invents_from
    get_item.invents_from
  end
  
  def weapon?
    ["Sword", "Great Sword", "Shortsword", "Spear", "Staff", "Knuckle", "Breaker", "Gun", "Scythe"].include?(item_type)
  end
  
  def non_weapon?
    ["Armour", "Ring"].include?(item_type)
  end    
  
end

app/models/invent_equip.rb
class InventEquip < ActiveRecord::Base
  #Similar reasoning here as in Recipes (with associations)
  def base
    Item.find_by_id(base_id)
  end
  def result
    Item.find_by_id(result_id)
  end

end

app/models/item.rb
class Item < ActiveRecord::Base
  #The goal of this project is more UI/front-end based, so I'm 
  #not fully utilizing associations at the moment.
  def components
    Recipe.find_all_by_result_id(id).map {|x| x.component}
  end
  
  def synthesizes
    Recipe.find_all_by_component_id(id).map {|x| x.result}.uniq
  end
  
  def invents
    InventEquip.find_all_by_base_id(id).map{|x| x.result}
  end
  
  def invents_from
    return InventEquip.find_all_by_result_id(self.id).map{|x| x.base}
  end
  
  def equippable?
    #accurate, but slower:
    #Equipment.exists?(:name=>name)
    
    #less accurate, faster 
    #(depends on all equipment existing, and fixed name for non-equippables)
    item_type != Item.non_item_name
  end
  
  def self.non_item_name
    return "Synthesis component"
  end
  
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  #associations not a primary concern of this project
  #add in future for code quality?
  def result
    Item.find_by_id(result_id)
  end
  def component
    Item.find_by_id(component_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery
    def silent(str)
        silent_model_eval(str)
    end
    
    def silent_model_eval(str)
        ActiveRecord::Base.logger.silence do
            return eval(str)
        end
    end

    def check_equip(item)
      {:name=> item.name, :equip=>item.equippable?}
    end
end

app/controllers/equipment_controller.rb
class EquipmentController < ApplicationController
    #equipment = plural, equip = single.
  def index
    @equipment = silent("Equipment.all")
    @item_types = silent("Equipment.uniq.pluck :item_type")
  end
  
  def show
    @equip = Equipment.find_by_name(params[:name])
    if @equip.nil?
    else
      @general = @equip.basic_stats.map
      @invents = @equip.invents_into.map {|x| x.name}
      @invents_from = @equip.invents_from.map {|x| x.name}
      @specs = @equip.spec_stats 
      @eqp_stats = @equip.eqp_stats
      @char_stats = @equip.char_stats
      @misc_stats = @equip.misc_stats
      
      temp = Item.find_by_name @equip.name
      @synthesizes = temp.synthesizes.map{|x| check_equip x}
      @components = temp.components.map{|x| check_equip x}
    end
  end
end

app/controllers/item_controller.rb
class ItemController < ApplicationController
  def index
    @items = silent("Item.order(:name)")
    
  end

  def show
    name = params[:name]
    @item = Item.find_by_name name
    @synthesizes = @item.synthesizes.map {|x| check_equip x}
    @components = @item.components.map{|x| check_equip x}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/equipment_helper.rb
module EquipmentHelper
end

app/helpers/item_helper.rb
module ItemHelper

  def show_best_path(item)
    if item.equippable?
      return show_equipment_path(item.name)
    else
      return show_item_path(item.name)
    end
  end
end

app/views/equipment/_stats.html.erb
<table class = "table table-hover table-bordered table-condensed">
    <thead>
      <tr>
        <td> <b>Level</b> </td>
        <%(1..5).each do |num| %>
          <td><b><%=num%></b></td>
        <%end%>
      </tr>
    </thead>
    <tbody>
      <% @eqp_stats.each do |field, values| %>
        <tr> 
          <td> <b><%= field.upcase%></b> </td> 
          <%values.each do |val|%>
            <td> <%=val%> </td>
          <%end%>
        </tr>
      <%end%>
      
      <tr ><%(1+5).times do%><td class = "divider"><%end%></td></tr>
      
      <% @char_stats.each do |field, values| %>
        <tr> 
          <td> <b><%= field.upcase%></b> </td> 
          <%values.each do |val|%>
            <td> <%=val%> </td>
          <%end%>
        </tr>
      <%end%>
    
      <tr ><%(1+5).times do%><td class = "divider"><%end%></td></tr>
    
      <% @misc_stats.each do |field, values| %>
        <tr> 
          <td> <b><%= field.upcase%></b> </td> 
          <%values.each do |val|%>
            <td> <%=val%> </td>
          <%end%>
        </tr>
      <%end%>
    </tbody>
  </table>

app/views/equipment/index.html.erb
<script type = "text/javascript">
    $(EL.setup)
</script>
<h1>Equipment list </h1>
<table class = "table table-striped table-bordered table-condensed" id = "itemTable">
    <thead>
        <strong><tr>
            <th id=header_name>
                <a id =sortby_name href = <%= home_path %>> Name </a> 
            </th> 
             <th id=header_item_type>
                <a id =sortby_item_type href = <%= home_path %>> Type </a> 
                <!--    <select multiple id = "item_type_filter" style="width: 110px;"> 
                  <option value="All"> All </option>
                            <% for type in @item_types%>
                    <option value=<%=type%>><%=type%></option>
                  <%end%>
                        </select> 
                -->    
				
              <div class=type_list style="display: none;">
                <%= check_box_tag "All"%>
                <!--<% for type in @item_types%>
                  <option value=<%=type%>><%=type%></option>
                <%end%> -->
              </div>
            </th>
        </tr></strong>
    </thead>
    <tbody>
        <% for equip in @equipment %>
            <tr id = <%= equip.name.gsub(/ /, "_")%>>
                <td id=name> <%=link_to show_equipment_path(equip.name) do equip.name end %></td>
                <td id=item_type> <%=equip.item_type%> </td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/equipment/show.html.erb
<h1> <%=@equip.name%> </h1>
<div class="clearfix">
<div id="column1" class="col3rd">
  <ul>
    <% @general.each do |field, value| %>
      <li> <b><%= field.capitalize%>: </b> <%= value%></li>
    <%end%>
    
   <%= render "shared/synth_info"%>
    
  </ul>
</div>
<div id="col2" class="col3rd">
  <ul>
    <% @specs.each do |field, value| %>
      <li> <b><%= field.capitalize%>: </b> <%= value%></li>
    <%end%>
    
    <li><b>Invents into:</b>
      <ul>
        <%if @invents.empty?%>
          <li> (nothing) </li>
        <%else%>
          <%@invents.each do |name| %>
            <li> <%=link_to show_equipment_path(name) do name end%> </li> 
          <%end%>
        <%end%>
      </ul>
    </li>
    <li><b>Invented from:</b>
      <ul>
        <%if @invents_from.empty?%>
          <li> (nothing) </li>
        <%else%>
          <%@invents_from.each do |name| %>
            <li> <%=link_to show_equipment_path(name) do name end%> </li> 
          <%end%>
        <%end%>
      </ul>
    </li>
  </ul>
</div>
<div id="col3" class="col3rd">
  <%= render "stats"%>
</div>
</div>
</ul>

app/views/item/index.html.erb
<script type = "text/javascript">
    $(IL.setup)
    
</script>
<h1>Item list </h1>
<table class = "table table-striped table-bordered table-condensed" id = "itemTable">
    <thead>
        <strong><tr>
            <th id=header_name>
                <a id =sortby_name href = <%= home_path %>> Name </a> 
            </th> 
             <th id=header_item_type>
                <a id =sortby_item_type href = <%= home_path %>> Type </a> 
            </th>
        </tr></strong>
    </thead>
    <tbody>
        <% for item in @items %>
            <tr id = <%= item.name.gsub(/ /, "_")%>>
                <td id=name> <%=link_to show_best_path(item) do item.name end%></td>
                <td id=item_type> <%=item.item_type%> </td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/item/show.html.erb
<h1> <%=@item.name%> </h1>
<p> *Not an equippable item </p>

<%= render "/shared/synth_info"%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<script type = "text/javascript">

</script>

<html>
<head>
  <title>Spectral Souls Item Guide</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  
  <style type = "text/css" media="screen">
        /* Override some defaults */
      html, body {
        background-color: #ffff;
     }
     .container {
       width : 800px;
     }
   </style>
</head>
<body>
    <!-- Navigation Bar -->
    <div class="navbar navbar-static-top navbar-inverse">
        <div class="navbar-inner">
            <p class = "brand"> Spectral Souls Item Guide: </p>
            
            <form action=<%=item_index_path%> style="float: left;width:auto;">
              <button class="btn" type="submit">All Items</button>
            </form>
            <p style="float: left;width:auto;margin-top:10px;"> --- </p>
            <form action=<%=home_path%> style="float: left;width:auto;">
              <button class="btn" type="submit">Equipment</button>
            </form>
            
        </div>
    </div>
    <!--<div class="background"></div>-->
    <div style="width:90%;margin:0 auto;">
      <p id=nojsmsg> Note: Some functionality is missing because you do not have JavaScript enabled. </p>
      <%= yield %>
      <footer class="footer"> 
        <p> Site made by Jason Teoh: jasontgame@gmail.com </p>
        <p> Credits: All game info comes from guides posted by swift412 on GameFAQs. </p>
      </footer>
    </div>

</body>

</html>

app/views/shared/_synth_info.html.erb
<li><b>Synthesis component of:</b>
    <ul>
      <%if @synthesizes.empty?%>
        <li> (nothing) </li>
      <%else%>
        <%@synthesizes.each do |item| %>
        <%name = item[:name]%>
          <li> 
            <%if item[:equip]%>
              <%=link_to show_equipment_path(name) do name end%>
            <%else%>
              <%=link_to show_item_path(name) do name end%>
            <%end%>
          </li>
        <%end%>
      <%end%>
    </ul>
  </li>
  
  <li><b>Synthesized from:</b>
    <ul>
      <%if @components.empty?%>
        <li> (nothing) </li>
      <%else%>
        <%@components.each do |item| %>
        <%name = item[:name]%>
          <li>   
            <%if item[:equip]%>
              <%=link_to show_equipment_path(name) do name end%>
            <%else%>
              <%=link_to show_item_path(name) do name end%>
            <%end%>
          </li>
        <%end%>
      <%end%>
    </ul>
  </li>